import 'package:flutter/widgets.dart';
import 'package:flutter_svg/flutter_svg.dart';

/// Names of the bundled flat wood-style UI icons (assets/icons/*.svg).
/// Generated by tool/icon/gen_ui_icons.py.
abstract final class WoodIcons {
  static const bowl = 'bowl';
  static const cube = 'cube';
  static const disk = 'disk';
  static const ring = 'ring';
  static const compound = 'compound';
  static const stave = 'stave';
  static const addRing = 'add_ring';
  static const removeRing = 'remove_ring';
  static const undo = 'undo';
  static const redo = 'redo';
  static const save = 'save';
  static const dimensions = 'dimensions';
  static const cutList = 'cut_list';
  static const lumber = 'lumber';
  static const grain = 'grain';
  static const rotate = 'rotate';
}

/// Renders one of the multi-colour wood icons. These carry their own wood
/// palette, so (unlike a Material [Icon]) they are not tinted by the ambient
/// icon colour; [opacity] dims them for a disabled look.
class WoodIcon extends StatelessWidget {
  const WoodIcon(this.name, {super.key, this.size = 20, this.opacity = 1.0});

  final String name;
  final double size;
  final double opacity;

  @override
  Widget build(BuildContext context) {
    final icon = SvgPicture.asset(
      'assets/icons/$name.svg',
      width: size,
      height: size,
    );
    return opacity >= 1.0 ? icon : Opacity(opacity: opacity, child: icon);
  }
}
